### PR TITLE
Linux

### PR DESCRIPTION
**Pull request by Unrealf1**

### CODE REVIEW

**Review by AlexanderPolyakov — CHANGES_REQUESTED** [review]
You don't need to put this in a pull request at all, as this is part of a homework.

**Review by AlexanderPolyakov — CHANGES_REQUESTED** [review]
These changes increase complexity at the moment (though making it more clean). Different approach needed. We generally don't want to fix warnings in 3rd party libraries at all. Fixes in our code is fine though.

**Comment by Unrealf1** [comment]
Fixed, I pushed last two commits to this branch by mistake :)

**Comment by Unrealf1** [comment]
> These changes increase complexity at the moment (though making it more clean). Different approach needed. We generally don't want to fix warnings in 3rd party libraries at all. Fixes in our code is fine though.

Fixed, I pushed last two commits to this branch by mistake :)

**Pull request merged**
